# Generated by Django 4.2.10 on 2026-03-10 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fine', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_records', to='loans.loan')),
            ],
            options={
                'db_table': 'returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('condition_on_return', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', help_text='Kondisi alat saat dikembalikan. Trigger DB akan update tools.condition jika lebih buruk.', max_length=15)),
                ('loan_item', models.ForeignKey(db_column='loan_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='loans.loanitem')),
                ('return_record', models.ForeignKey(db_column='return_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
            ],
            options={
                'db_table': 'return_items',
            },
        ),
    ]
