# Generated by Django 4.2.10 on 2026-03-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='processed_by',
            field=models.ForeignKey(db_column='processed_by', on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_record', 'loan_item')},
        ),
    ]
