# Generated by Django 4.2.10 on 2026-03-10 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('qr_code', models.CharField(editable=False, help_text='Token unik yang di-encode menjadi QR label alat.', max_length=64, unique=True)),
                ('stock_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_available', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='categories.category')),
            ],
            options={
                'db_table': 'tools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['qr_code'], name='tools_qr_code_18a6f6_idx'), models.Index(fields=['category'], name='tools_categor_c67261_idx'), models.Index(fields=['is_active'], name='tools_is_acti_efb812_idx')],
            },
        ),
    ]
