# Generated by Django 4.2.10 on 2026-03-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['department'], name='tools_departm_33eef5_idx'),
        ),
    ]
